import type { Metadata } from "next";
import { Geist, Geist_Mono, Lora } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/tanstack-query-providers";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const lora = Lora({
//   variable: "--font-lora",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Soubless User Portal",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${lora.variable} antialiased`}
      >
        <QueryProvider>
          {/* <CustomThemeProvider> */}
            {children}
          {/* </CustomThemeProvider> */}
        </QueryProvider>
      </body>
    </html>
  );
}
